import type {
  AnalyzedTrade,
  ResearchCapabilities,
  ResearchRunResponse,
  ResearchCompareResponse,
  SavedConfig,
} from "@/lib/research/types";
export const capabilities: ResearchCapabilities = {
  executionModes: ["SEQUENTIAL", "FIXED_ENTRY_COHORT"],
  exitStrategies: [
    { type: "CURRENT", params: [] },
    {
      type: "CHANDELIER",
      params: [
        { name: "activationPct", default: 0.005, min: 0 },
        { name: "atrMultiplier", default: 2, minExclusive: 0 },
      ],
    },
  ],
  executionTimeframes: {
    "4h": ["1m", "5m", "15m", "30m", "1h", "2h", "4h"],
    "15m": ["1m", "5m", "15m"],
  },
  limits: { maxRangeDays: 366, maxExitVariants: 10, maxCandles: 20000 },
  initialBalanceDefault: 1000,
  analysis: { mfeExcursionThresholds: [0.0025] },
};
export const configs: SavedConfig[] = [
  {
    id: 7,
    name: "XRP 4H",
    isActive: true,
    symbol: "XRPUSDT",
    timeframe: "4h",
    trendTimeframe: "1d",
  },
];
export const first: AnalyzedTrade = {
  entryId: "LONG:1000:2000",
  trade: {
    side: "LONG",
    reason: "Signal",
    signalTime: 1000,
    entryTime: 2000,
    exitTime: 3000,
    entryPrice: 100,
    exitPrice: 99,
    pnl: -2,
    fee: 1,
    funding: 0,
    result: "LOSS",
    exitReason: "stop",
    candlesHeld: 3,
    maxFavorable: 110,
    maxAdverse: 99,
    maxFavorablePnl: 10,
    maxAdversePnl: -1,
    candlesToMaxFavorable: 1,
    candlesToMaxAdverse: 2,
    adverseBeforeFavorable: false,
    wasProfit: true,
    peakPnlBeforeLoss: 10,
  },
  metrics: {
    grossRealizedPnl: -1,
    mfeCaptureRatio: -0.1,
    peakGiveback: 11,
    peakGivebackRatio: 1.1,
    favorablePricePct: 0.1,
    maxFavorablePct: 0.1,
    greenToRed: true,
  },
};
export const second: AnalyzedTrade = {
  ...first,
  entryId: "LONG:4000:5000",
  trade: {
    ...first.trade,
    signalTime: 4000,
    entryTime: 5000,
    result: "WIN",
    pnl: 5,
  },
  metrics: { ...first.metrics, greenToRed: false, mfeCaptureRatio: 0.5 },
};
export const single: ResearchRunResponse = {
  metadata: {
    configId: 7,
    symbol: "XRPUSDT",
    timeframe: "4h",
    trendTimeframe: "1d",
    executionTimeframe: "4h",
    from: "2026-01-01T00:00:00.000Z",
    to: "2026-04-01T00:00:00.000Z",
    executionMode: "SEQUENTIAL",
  },
  variantId: "CURRENT",
  exitStrategy: { type: "CURRENT" },
  greenThresholdPct: 0.0025,
  summary: {
    totalTrades: 2,
    wins: 1,
    losses: 1,
    scratches: 0,
    winRate: 0.5,
    initialBalance: 1000,
    finalBalance: 1003,
    totalPnl: 3,
    totalFees: 2,
    totalFunding: 0,
    signalsEvaluated: 10,
    signalsExecuted: 2,
    signalsRejected: 0,
  },
  quality: {
    evaluatedEntries: 2,
    wins: 1,
    losses: 1,
    scratches: 0,
    winRate: 0.5,
    totalPnl: 3,
    expectancy: 1.5,
    profitFactor: 2.5,
    profitFactorStatus: "DEFINED",
    maxDrawdownAbsolute: 2,
    maxDrawdownPct: 0.002,
    avgMfe: 10,
    avgMae: -1,
    avgMfeCaptureRatio: 0.2,
    medianMfeCaptureRatio: 0.2,
    avgPeakGiveback: 8,
    medianPeakGiveback: 8,
    greenToRedCount: 1,
    greenToRedRate: 0.5,
    avgCandlesHeld: 3,
    medianCandlesHeld: 3,
    exitReasons: { stop: 2, tp: 0, timeout: 0, "trailing-crossed": 0 },
  },
  excursion: {
    totalTrades: 2,
    distribution: {mean: .1, median: .1, p25: .1, p75: .1, p90: .1, max: .1},
    thresholds: [{thresholdPct: .0025, reachedCount: 2, reachedRate: 1,
      finishedPositiveCount: 1, finishedNegativeCount: 1, finishedScratchCount: 0,
      greenToRedCount: 1, greenToRedRate: .5, avgRealizedPnl: 1.5, totalRealizedPnl: 3,
      avgMfeCaptureRatio: .2, medianMfeCaptureRatio: .2, avgPeakGiveback: 8,
      medianPeakGiveback: 8, avgCandlesHeld: 3}],
    largestExcursionLosses: [first],
  },
  trades: [first, second],
};
export const comparison: ResearchCompareResponse = {
  metadata: {
    ...single.metadata,
    executionMode: "FIXED_ENTRY_COHORT",
    entries: 2,
    cohortSource: "CURRENT_SEQUENTIAL",
  },
  results: [
    single,
    {
      ...single,
      variantId: "CHANDELIER:activation=0.005:atr=2",
      exitStrategy: {
        type: "CHANDELIER",
        params: { activationPct: 0.005, atrMultiplier: 2 },
      },
      trades: [
        { ...second, trade: { ...second.trade, pnl: 42 } },
        { ...first, trade: { ...first.trade, pnl: 17 } },
      ],
    },
  ],
};
