import type {
  SignalDetail,
  SignalFacets,
  SignalListResponse,
  SignalMeta,
} from "@/lib/signals/types";

export const meta: SignalMeta = {
  statuses: [
    "SIGNAL_GENERATED",
    "AWAITING_CONFIRMATION",
    "REJECTED",
    "EXECUTION_ATTEMPTED",
    "EXECUTED",
    "EXECUTION_FAILED",
  ],
  rejectionCodes: [
    "BOT_PAUSED",
    "POSITION_ALREADY_OPEN",
    "CONFIRMATION_PENDING",
    "CONFIRMATION_PULLBACK_EXCEEDED",
    "CONFIRMATION_TIMEOUT",
    "DAILY_KILL_SWITCH",
    "PRICE_DRIFT_EXCEEDED",
    "CONCURRENT_OPEN_IN_PROGRESS",
    "ORDER_FAILED",
    "UNKNOWN",
  ],
  rejectionStages: ["STRATEGY_RISK", "EXECUTION"],
  sides: ["LONG", "SHORT"],
  modes: ["PAPER", "LIVE"],
  limits: {
    defaultLimit: 25,
    maxLimit: 100,
    maxSymbolLength: 20,
    maxSignalTypeLength: 120,
  },
};

export const facets: SignalFacets = {
  symbols: ["BTCUSDT", "XRPUSDT"],
  signalTypes: ["Stoch RSI cruce", "VWAP Reversion alcista"],
  rejectionCodes: ["CONFIRMATION_TIMEOUT", "POSITION_ALREADY_OPEN"],
};

export const list: SignalListResponse = {
  items: [
    {
      id: 1,
      mode: "PAPER",
      symbol: "XRPUSDT",
      timeframe: "4h",
      signalType: "VWAP Reversion alcista",
      side: "LONG",
      score: 4,
      status: "EXECUTED",
      rejectionCode: null,
      decisionTime: "2026-10-01T13:00:00.000Z",
      tradeId: 812,
      configHash: "a83f2176c0c0a604fa9967aada6719bb",
      createdAt: "2026-10-01T13:00:01.000Z",
      exitStrategyType: "ADAPTIVE_CHANDELIER",
    },
    {
      id: 2,
      mode: "PAPER",
      symbol: "XRPUSDT",
      timeframe: "4h",
      signalType: "Stoch RSI cruce",
      side: "LONG",
      score: 3.2,
      status: "REJECTED",
      rejectionCode: "POSITION_ALREADY_OPEN",
      decisionTime: "2026-10-01T17:00:00.000Z",
      tradeId: null,
      configHash: "a83f2176c0c0a604fa9967aada6719bb",
      createdAt: "2026-10-01T17:00:01.000Z",
      exitStrategyType: null,
    },
    {
      id: 3,
      mode: "LIVE",
      symbol: "XRPUSDT",
      timeframe: "4h",
      signalType: "VWAP Reversion bajista",
      side: "SHORT",
      score: 5.1,
      status: "REJECTED",
      rejectionCode: "CONFIRMATION_TIMEOUT",
      decisionTime: "2026-10-01T21:00:00.000Z",
      tradeId: null,
      configHash: "b14c9908d1e2f3a4b5c6d7e8f9a0b1c2",
      createdAt: "2026-10-01T21:00:01.000Z",
      exitStrategyType: null,
    },
  ],
  page: 1,
  limit: 25,
  total: 3,
  totalPages: 1,
  summary: {
    signals: 42,
    executed: 18,
    rejected: 24,
    executionRate: 18 / 42,
    byStatus: { EXECUTED: 18, REJECTED: 24 },
    score: {
      all: { scored: 42, average: 3.8, median: 4 },
      executed: { scored: 18, average: 4.2, median: 4 },
      rejected: { scored: 24, average: 3.5, median: 3.5 },
    },
  },
};

export const empty: SignalListResponse = {
  items: [],
  page: 1,
  limit: 25,
  total: 0,
  totalPages: 0,
  summary: {
    signals: 0,
    executed: 0,
    rejected: 0,
    executionRate: null,
    byStatus: {},
    score: {
      all: { scored: 0, average: null, median: null },
      executed: { scored: 0, average: null, median: null },
      rejected: { scored: 0, average: null, median: null },
    },
  },
};

export const paged: SignalListResponse = {
  ...list,
  total: 60,
  totalPages: 3,
};

export const detail: SignalDetail = {
  id: 1,
  mode: "PAPER",
  symbol: "XRPUSDT",
  timeframe: "4h",
  signalCandleOpenTime: "2026-10-01T08:00:00.000Z",
  signalCandleCloseTime: "2026-10-01T12:00:00.000Z",
  decisionTime: "2026-10-01T13:00:00.000Z",
  createdAt: "2026-10-01T13:00:01.000Z",
  side: "LONG",
  signalType: "VWAP Reversion alcista",
  score: 4,
  reason: "VWAP Reversion alcista | Score: 4 (+ Tendencia a favor, Sobre VWAP)",
  status: "EXECUTED",
  rejectionStage: null,
  rejectionCode: null,
  rejectionDetail: null,
  decisionPrice: 1.4032,
  expectedEntryPrice: 1.4038,
  configId: 14,
  configHash: "a83f2176c0c0a604fa9967aada6719bb",
  signalIdentity: "36ab0a8e968ea49ea6c5e6a0",
  contextVersion: 1,
  context: {
    price: 1.4032,
    rsi: 43.2,
    prevRsi: 40.8,
    stochRsi: { k: 18.4, d: 14.1, prevK: 11.2, prevD: 9.8 },
    ema: { fast: 1.4032, slow: 1.3978, spreadPct: 0.0039 },
    vwap: 1.4007,
    priceAboveVwap: true,
    atr: 0.029,
    atrPct: 0.0194,
    atrExpanding: true,
    bb: {
      upper: 1.5188,
      middle: 1.4958,
      lower: 1.4728,
      bandWidth: 3.07,
      squeeze: true,
      squeezeRelease: false,
    },
    volume: { current: 100686204, average: 138441672, relative: 0.72, isHigh: false },
    // `strength` null a propósito: la UI debe mostrar "—", nunca 0.
    trend: { direction: "BULLISH", strength: null },
  },
  scoreBreakdown: {
    signal: "LONG",
    selectedSide: "LONG",
    scores: { LONG: 4, SHORT: 0 },
    eventCount: { LONG: 1, SHORT: 0 },
    factors: {
      LONG: [
        {
          code: "VWAP_REVERSION_BULLISH",
          label: "VWAP Reversion alcista",
          category: "EVENT",
          points: 2,
        },
        {
          code: "HTF_TREND_ALIGNED",
          label: "Tendencia a favor",
          category: "CONFIRMATION",
          points: 1,
        },
        {
          code: "ABOVE_VWAP",
          label: "Sobre VWAP",
          category: "CONFIRMATION",
          points: 1,
        },
      ],
      SHORT: [
        {
          code: "HTF_TREND_OPPOSED",
          label: "Tendencia en contra",
          category: "CONFIRMATION",
          points: -1,
        },
      ],
    },
    selectedTotal: 4,
    reasonCodes: ["VWAP_REVERSION_BULLISH"],
  },
  executionAttemptedAt: "2026-10-01T13:00:05.000Z",
  orderAcknowledgedAt: "2026-10-01T13:00:06.000Z",
  clientOrderId: "cli-812",
  exchangeOrderId: "ex-99",
  trade: {
    id: 812,
    type: "LONG",
    entryPrice: 1.4041,
    exitPrice: 1.42,
    stopLoss: 1.38,
    takeProfit: 1.45,
    result: "WIN",
    pnl: 3.21,
    reason: "take-profit",
    openedAt: "2026-10-01T13:00:06.000Z",
    closedAt: "2026-10-02T01:00:00.000Z",
    quantity: 20,
    exitStrategyType: "ADAPTIVE_CHANDELIER",
  },
  configSnapshot: {
    symbol: "XRPUSDT",
    timeframe: "4h",
    scoreMinToEnter: 3,
    scoreTrendAligned: 1,
    onlyLong: true,
    exitStrategy: {
      type: "ADAPTIVE_CHANDELIER",
      params: {
        activationPct: 0.0025,
        lowAtrMultiplier: 0.8,
        normalAtrMultiplier: 1,
        highAtrMultiplier: 1.4,
        volatilityWindow: 100,
        lowPercentile: 25,
        highPercentile: 75,
      },
    },
  },
  exitStrategy: {
    type: "ADAPTIVE_CHANDELIER",
    params: {
      activationPct: 0.0025,
      lowAtrMultiplier: 0.8,
      normalAtrMultiplier: 1,
      highAtrMultiplier: 1.4,
      volatilityWindow: 100,
      lowPercentile: 25,
      highPercentile: 75,
    },
  },
  causalTiming: true,
};

export const rejectedDetail: SignalDetail = {
  ...detail,
  id: 2,
  status: "REJECTED",
  rejectionStage: "EXECUTION",
  rejectionCode: "POSITION_ALREADY_OPEN",
  rejectionDetail: "ya hay una posición activa",
  expectedEntryPrice: null,
  executionAttemptedAt: null,
  orderAcknowledgedAt: null,
  clientOrderId: null,
  exchangeOrderId: null,
  trade: null,
  configSnapshot: null,
  exitStrategy: null,
};
